# Generated by Django 3.1.3 on 2020-11-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0002_auto_20201119_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmations',
            new_name='EmailConfirmation',
        ),
    ]
