# Generated by Django 3.1.3 on 2020-11-21 12:02

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0003_auto_20201121_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='interestCheckId',
            new_name='raffleEntryId',
        ),
        
        migrations.AlterField(
            model_name='emailconfirmation',
            name='raffleEntryId',
            field=models.ForeignKey(on_delete=models.CASCADE, to="InterestCheck", db_constraint=False),
        ),
        
        migrations.RenameModel(
            old_name='InterestCheck',
            new_name='RaffleEntry',
        ),

        migrations.AlterField(
            model_name='emailconfirmation',
            name='raffleEntryId',
            field=models.ForeignKey(on_delete=models.CASCADE, to='RaffleEntry'),
        ),
    ]
