# Generated by Django 3.1.3 on 2020-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201121_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffleentry',
            options={'verbose_name': 'Raffle Entry', 'verbose_name_plural': 'Raffle entries'},
        ),
        migrations.AddField(
            model_name='importantdate',
            name='desc',
            field=models.CharField(default='', max_length=254, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
