# Generated by Django 3.1.3 on 2020-11-22 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0005_auto_20201122_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='riverraftingteam',
            name='join_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
