# Generated by Django 3.1.2 on 2020-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0005_auto_20201122_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverRaftingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifevest', models.IntegerField()),
                ('wetsuit', models.IntegerField()),
                ('helmet', models.IntegerField()),
                ('raft_fee', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='riverraftingteam',
            name='payment_initialized',
            field=models.BooleanField(default=False, verbose_name='Payment initialized'),
        ),
        migrations.AddField(
            model_name='riverraftinguser',
            name='helmet_size',
            field=models.CharField(blank=True, choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2, null=True, verbose_name='Helmet size'),
        ),
        migrations.AddField(
            model_name='riverraftinguser',
            name='wetsuite_size',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, null=True, verbose_name='Wetsuit size'),
        ),
    ]
