# Generated by Django 3.1.2 on 2020-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0006_auto_20201122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverraftinguser',
            name='lifevest_size',
            field=models.CharField(blank=True, choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2, null=True, verbose_name='Lifevest size'),
        ),
    ]
