# Generated by Django 3.1.3 on 2020-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0007_auto_20201122_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverraftingcost',
            name='helmet',
            field=models.IntegerField(verbose_name='Helmet (kr)'),
        ),
        migrations.AlterField(
            model_name='riverraftingcost',
            name='lifevest',
            field=models.IntegerField(verbose_name='Lifevest (kr)'),
        ),
        migrations.AlterField(
            model_name='riverraftingcost',
            name='raft_fee',
            field=models.IntegerField(verbose_name='Raft fee (kr)'),
        ),
        migrations.AlterField(
            model_name='riverraftingcost',
            name='wetsuit',
            field=models.IntegerField(verbose_name='Wetsuit (kr)'),
        ),
    ]
