# Generated by Django 3.1.3 on 2020-11-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0007_auto_20201122_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverraftingteam',
            name='name',
            field=models.CharField(default='Radical Nightingales', max_length=254, verbose_name='Team name'),
        ),
    ]
