# Generated by Django 3.1.3 on 2020-11-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0008_auto_20201122_2003'),
        ('registrationSystem', '0008_auto_20201126_1756'),
    ]

    operations = [
    ]
