# Generated by Django 3.1.3 on 2020-11-26 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0009_merge_20201126_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='riverraftingteam',
            name='name',
            field=models.CharField(default='Illegal Caterpillars', max_length=254, verbose_name='Team name'),
        ),
    ]
