# Generated by Django 3.1.3 on 2020-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0009_merge_20201126_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='person_nr',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='riverraftingteam',
            name='name',
            field=models.CharField(default='Wine Pudus', max_length=254, verbose_name='Team name'),
        ),
    ]
