# Generated by Django 3.1.3 on 2020-11-26 19:44

from django.db import migrations, models
import registrationSystem.models.river_rafting.river_rafting_team


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0010_auto_20201126_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverraftingteam',
            name='name',
            field=models.CharField(default=registrationSystem.models.river_rafting.river_rafting_team.get_cool_team_name, max_length=254, verbose_name='Team name'),
        ),
    ]
