# Generated by Django 3.1.3 on 2020-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0012_auto_20201128_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='riverraftinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
