# Generated by Django 3.1.1 on 2020-09-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=254)),
                ('mail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('mail confirmed', 'Mail-Confirmed'), ('won', 'Won'), ('lost', 'Lost'), ('reapplying', 'Reapplying'), ('declined', 'Declined')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('namn', models.CharField(max_length=254)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('is_utn_member', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiverraftingGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrationSystem.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('registrationSystem.group',),
        ),
        migrations.CreateModel(
            name='RiverraftingUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrationSystem.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('registrationSystem.user',),
        ),
    ]
