# Generated by Django 3.1.1 on 2020-09-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrationSystem.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='belongs_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrationSystem.group'),
        ),
    ]
