# Generated by Django 3.1.2 on 2020-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0002_auto_20201001_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='status',
            field=models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('mail confirmed', 'Mail-Confirmed'), ('won', 'Won'), ('lost', 'Lost'), ('reapplying', 'Reapplying'), ('pending', 'Pending'), ('declined', 'Declined')], default='mail unconfirmed', max_length=20),
        ),
    ]
