# Generated by Django 3.1.2 on 2020-11-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0002_auto_20201121_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiverraftingCosts',
            new_name='RiverraftingCost',
        ),
    ]
