# Generated by Django 3.1.2 on 2020-10-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0002_auto_20201001_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestcheck',
            old_name='personnr',
            new_name='person_nr',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='namn',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personnr',
            new_name='person_nr',
        ),
    ]
