# Generated by Django 3.1.2 on 2020-10-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201006_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='status',
            field=models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('waiting', 'Waiting'), ('won', 'Won'), ('lost', 'Lost'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20),
        ),
    ]
