# Generated by Django 3.1.1 on 2020-10-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201006_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongs_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrationSystem.group'),
        ),
    ]
