# Generated by Django 3.1.2 on 2020-10-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201006_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='status',
            field=models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('in the raffle', 'In the raffle'), ('confirmed', 'Confirmed'), ('won', 'Won'), ('lost', 'Lost'), ('must reapply', 'Must reapply'), ('pending', 'Pending'), ('declined', 'Declined')], max_length=20),
        ),
    ]
