# Generated by Django 3.1.2 on 2020-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201006_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcheck',
            name='is_utn_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_utn_member',
            field=models.BooleanField(default=False),
        ),
    ]
