# Generated by Django 3.1.2 on 2020-10-28 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0004_auto_20201006_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interestCheckId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationSystem.interestcheck')),
            ],
        ),
    ]
