# Generated by Django 3.1.1 on 2020-10-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0005_auto_20201027_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='belongs_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrationSystem.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_utn_member',
            field=models.BooleanField(verbose_name='UTN Member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=254, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_nr',
            field=models.CharField(max_length=13, verbose_name='Person number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_nr',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
