# Generated by Django 3.1.2 on 2020-11-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0005_auto_20201031_1836'),
        ('registrationSystem', '0005_auto_20201027_1903'),
    ]

    operations = [
    ]
