# Generated by Django 3.1.3 on 2020-11-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0006_merge_20201101_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='status',
            field=models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('waiting', 'Waiting'), ('won', 'Won'), ('lost', 'Lost'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed')], default='mail unconfirmed', max_length=20),
        ),
    ]
