# Generated by Django 3.1.2 on 2020-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0006_merge_20201101_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverRaftingRaffleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('drawn', 'Drawn'), ('closed', 'Closed')], max_length=20)),
            ],
            options={
                'verbose_name': 'The River Rafting Raffle',
                'verbose_name_plural': 'The River Rafting Raffle',
            },
        ),
    ]
