# Generated by Django 3.1.2 on 2020-11-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0006_merge_20201101_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcheck',
            name='status',
            field=models.CharField(choices=[('mail unconfirmed', 'Mail-Unconfirmed'), ('waiting', 'Waiting'), ('won', 'Won'), ('lost', 'Lost'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='mail unconfirmed', max_length=20),
        ),
    ]
