# Generated by Django 3.1.3 on 2020-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0007_auto_20201103_1932'),
        ('registrationSystem', '0007_auto_20201105_1832'),
        ('registrationSystem', '0007_riverraftingrafflestate'),
    ]

    operations = [
    ]
