# Generated by Django 3.1.2 on 2020-11-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0007_auto_20201101_1051'),
        ('registrationSystem', '0006_merge_20201101_1351'),
    ]

    operations = [
    ]
