# Generated by Django 3.1.1 on 2020-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0007_riverraftinguser_lifevest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_nr',
            field=models.CharField(max_length=13, unique=True, verbose_name='Person number'),
        ),
    ]
