# Generated by Django 3.1.1 on 2020-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0008_auto_20201029_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riverraftinguser',
            name='lifevest_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2),
        ),
    ]
