# Generated by Django 3.1.1 on 2020-11-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0005_auto_20201031_1836'),
        ('registrationSystem', '0011_auto_20201031_1734'),
    ]

    operations = [
    ]
