# Generated by Django 3.1.1 on 2020-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0012_merge_20201101_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='riverraftinggroup',
            name='environment_raft',
            field=models.BooleanField(default=False, verbose_name='I want an environmentally friendly raft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Team name'),
        ),
        migrations.AlterField(
            model_name='riverraftinguser',
            name='lifevest_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], max_length=2, verbose_name='Lifevest size'),
        ),
    ]
