# Generated by Django 3.1.1 on 2020-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0013_auto_20201101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='riverraftinggroup',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Number'),
        ),
        migrations.AddField(
            model_name='riverraftinggroup',
            name='presentation',
            field=models.CharField(default=None, max_length=250, verbose_name='Presentation'),
            preserve_default=False,
        ),
    ]
