# Generated by Django 3.1.1 on 2020-11-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationSystem', '0006_merge_20201101_1351'),
        ('registrationSystem', '0016_auto_20201101_1724'),
    ]

    operations = [
    ]
